language: node_js
node_js:
  - 8
  - 10
  - 13
os:
  - osx
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use --delete-prefix $TRAVIS_NODE_VERSION
  - brew update
install:
  - npm install
script:
  - npm test
  - npm run test:coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
